# Generated by Django 5.1.1 on 2024-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/photo",
                verbose_name="изображение",
            ),
        ),
    ]
